services:
  mysql:
    container_name: mysql
    image: mysql
    restart: always
    environment:
      - 'MYSQL_DATABASE=authenticate_db'
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_PASSWORD=root'
    ports:
      - "3306:3306"
    networks:
      - mysql
    volumes:
      - mysql:/data/mysql

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - zipkin

networks:
  mysql:
    driver: bridge
  zipkin:
    driver: bridge

volumes:
  mysql: