eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: tasks
          uri: http://localhost:8446
          predicates:
            - Path=/api/v1/tasks/**
        - id: guidelines
          uri: http://localhost:8445
          predicates:
            - Path=/api/v1/guidelines/**
management:
  tracing:
    sampling:
      probability: 1.0